import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
    
  <div className={styles.container}>
    <Head>
    <title>ExerciseDB | Home</title> 
    <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1 className={styles.title}>ExerciseDB</h1>
    <p className={styles.text}>Working-Out is beneficial for your health. We have a huge database of exercise examples to choose from.</p>
    <div>
    <Link href="/exercises/Menu"><a className={styles.btn}>Get In Shape!</a></Link>
    
    </div>
    
  
  </div>
    </>
  )
}